// web/portal/src/layouts/components/header/UserCenter.tsx
/** Author: Charlie */

import { useEffect } from 'react'
import { Avatar, Button, Dropdown, Modal, Space, Tooltip, Typography, message } from 'antd'
import {
  HomeOutlined,
  LogoutOutlined,
  SettingOutlined,
  UserOutlined,
} from '@ant-design/icons'
import type { DropdownProps, MenuProps } from 'antd'
import { useLocation, useNavigate } from 'react-router-dom'
import { resolveFileUrl } from '@/utils/file'
import { useAuthStore } from '@/stores/auth'

type Props = {
  compact?: boolean
  placement?: DropdownProps['placement']
}

export function UserCenter({ compact = false, placement = 'bottomRight' }: Props) {
  const navigate = useNavigate()
  const location = useLocation()
  const userInfo = useAuthStore((s) => s.userInfo)
  const ensureSession = useAuthStore((s) => s.ensureSession)
  const logout = useAuthStore((s) => s.logout)

  const loggedIn = Boolean(userInfo?.accountId)

  useEffect(() => {
    void ensureSession()
  }, [ensureSession])

  if (!loggedIn) {
    if (compact) {
      return (
        <Tooltip title="登录" placement="right">
          <Button
            type="text"
            className="!h-10 !w-10 !px-0"
            icon={<UserOutlined />}
            aria-label="登录"
            onClick={() => navigate('/auth/login')}
          />
        </Tooltip>
      )
    }

    return (
      <Space size={8}>
        <Button onClick={() => navigate('/auth/register')}>注册</Button>
        <Button type="primary" onClick={() => navigate('/auth/login')}>
          登录
        </Button>
      </Space>
    )
  }

  const displayName = userInfo?.nickname || userInfo?.account || '用户'
  const avatarSrc = resolveFileUrl(userInfo?.avatar)

  const items: MenuProps['items'] = [
    {
      key: 'profile',
      icon: <UserOutlined />,
      label: '个人主页',
    },
    {
      key: 'userCenter',
      icon: <SettingOutlined />,
      label: '账号设置',
    },
    { type: 'divider' },
    {
      key: 'home',
      icon: <HomeOutlined />,
      label: '首页',
    },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
    },
  ]

  const onClick: MenuProps['onClick'] = ({ key }) => {
    if (key === 'profile') {
      navigate('/profile')
      return
    }
    if (key === 'userCenter') {
      navigate('/usercenter')
      return
    }
    if (key === 'home') {
      navigate('/')
      return
    }
    if (key === 'logout') {
      Modal.confirm({
        title: '退出登录',
        content: '确定退出当前账号？',
        okText: '确认',
        cancelText: '取消',
        onOk: async () => {
          await logout(location.pathname)
          message.success('已退出登录')
        },
      })
    }
  }

  const avatarBtn = (
    <Dropdown menu={{ items, onClick }} trigger={['click']} placement={placement}>
      <Space className="cursor-pointer select-none" size={8}>
        <Avatar src={avatarSrc} icon={<UserOutlined />} size={compact ? 32 : 'default'} />
        {compact ? null : (
          <Typography.Text className="hidden max-w-28 truncate md:inline">
            {displayName}
          </Typography.Text>
        )}
      </Space>
    </Dropdown>
  )

  if (compact) {
    return <div className="flex flex-col items-center gap-2">{avatarBtn}</div>
  }

  return <Space size={8}>{avatarBtn}</Space>
}

// web/admin/src/layouts/components/header/UserCenter.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import type { DropdownOption } from 'naive-ui'
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { renderIcon } from '@/utils/icon'
import { resolveFileUrl } from '@/utils'
import { useAuthStore } from '@/stores'

const router = useRouter()
const authStore = useAuthStore()
const homePath = import.meta.env.VITE_HOME_PATH

const displayName = computed(() => authStore.userInfo?.nickname || '-')

const avatar = computed(() => resolveFileUrl(authStore.userInfo?.avatar))
const avatarImgProps = { referrerPolicy: 'no-referrer' } as any

// 桌面端用户菜单项。项目首页使用环境配置路径。
const options = computed<DropdownOption[]>(() => [
  {
    label: '个人中心',
    key: 'userCenter',
    icon: renderIcon('icon-park-outline:user'),
  },
  {
    type: 'divider',
    key: 'divider-1',
  },
  {
    label: '项目首页',
    key: 'home',
    icon: renderIcon('icon-park-outline:home'),
  },
  {
    label: '退出登录',
    key: 'logout',
    icon: renderIcon('icon-park-outline:logout'),
  },
])

// 根据下拉菜单 key 分发行为；保留弹窗确认可以避免后续接入真实登出时误触。
function handleSelect(key: string | number) {
  if (key === 'userCenter') {
    router.push('/usercenter')
  }
  if (key === 'home') {
    router.push(homePath)
  }
  if (key === 'logout') {
    window.$dialog.info({
      title: '退出登录',
      content: '确定退出当前账号？',
      positiveText: '确认',
      negativeText: '取消',
      onPositiveClick: async () => {
        await authStore.logout()
        window.$message.success('已退出登录')
      },
    })
  }
}
</script>

<template>
  <n-dropdown trigger="click" :options="options" @select="handleSelect">
    <div class="flex items-center gap-2">
      <n-avatar
        v-if="avatar"
        round
        class="cursor-pointer"
        :src="avatar"
        :img-props="avatarImgProps"
      />
      <n-avatar v-else round class="cursor-pointer">
        <NovaIcon icon="icon-park-outline:user" />
      </n-avatar>
      <span class="hidden md:inline">{{ displayName }}</span>
    </div>
  </n-dropdown>
</template>
